export const MODAL_TYPE_NOTIFICATION = 'MODAL_TYPE_NOTIFICATION';
export const MODAL_TYPE_CONFIRMATION = 'MODAL_TYPE_CONFIRMATION';
export const MODAL_TYPE_EDITPROFILE = 'MODAL_TYPE_EDITPROFILE';
export const MODAL_TYPE_ADMINEDITPROFILE = 'MODAL_TYPE_ADMINEDITPROFILE';
export const MODAL_TYPE_UPGRADEMEMBERSHIP = 'MODAL_TYPE_UPGRADEMEMBERSHIP';
export const MODAL_TYPE_ADMINUPGRADEMEMBERSHIP = 'MODAL_TYPE_ADMINUPGRADEMEMBERSHIP';
export const MODAL_TYPE_DELETEMEMBER = 'MODAL_TYPE_DELETEMEMBER';
export const MODAL_TYPE_LOGIN = 'MODAL_TYPE_LOGIN';